cabinet/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.conf.urls import include
from . import views
from django.contrib import admin
from django.conf.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [

        url(r'^$', views.lit_work_list, name='lit_work_list'),

        # поиск по леммам и текстам
        url(r'^search/$', views.work_filters, name='work_filters'),
        url(r'^search/results/$', views.concordance, name='concordance'),
        url(r'^search/filters/$', views.work_results, name='work_results'),
        url(r'^search/(?P<pk>[0-9]+)/$', views.view_paragraph, name='view_paragraph'),
        url(r'^search/(?P<pk>[0-9]+)/edit/$', views.word_edit, name='markup_edit'),
        url(r'^search/cql/$', views.cql, name='cql'),
        url(r'^search/cql/query$', views.cql_search, name='cql_search'),
        url(r'^search/save/$', views.save_search, name='save_search'),

        # действия в личном кабинете
        url(r'^accounts/', include('registration.urls')),
        url(r'^accounts/(?P<pk>[0-9]+)/$', views.account, name='account'),
        url(r'^accounts/(?P<pk>[0-9]+)/edit/$', views.account_form, name='account_form'),
        url(r'^accounts/login$',  auth_views.LoginView.as_view(), name='login'),
        url(r'^accounts/logout/$', views.logout),

        # регистрация и авторизация
        url(r'^select2/', include('django_select2.urls')),
        url(r'^reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_confirm , name='reset_confirm'),
        url(r'^reset/$', views.reset, name='reset'),
        url(r'^accounts/password/reset/$',auth_views.password_reset, {'post_reset_redirect' : '/accounts/password/reset/done/'}),
        url(r'^accounts/password/reset/done/$', auth_views.password_reset_done),
        url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect' : '/accounts/password/done/'}, name='password_reset_confirm'),
        url(r'^accounts/password/complete/$', auth_views.password_reset_complete),
        url(r'^admin/(.*)', include(admin.site.urls)),

        # произведение
        url(r'^work/new/$', views.work_new, name='work_new'),
        url(r'^work/(?P<pk>[0-9]+)/$', views.work_detail, name='work_detail'),
        url(r'^work/(?P<pk>[0-9]+)/edit/$', views.work_edit, name='work_edit'),
        url(r'^work/(?P<pk>[0-9]+)/mark/$', views.mark_up, name='mark_up'),
        url(r'^work/(?P<pk>[0-9]+)/sentences/$', views.sentences, name='sentences'),
        url(r'^work/(?P<pk>[0-9]+)/analysis/$', views.analysis, name='analysis'),
        url(r'^work/(?P<pk>[0-9]+)/add_authors/$', views.add_authors, name='add_authors'),

        # коллекции, издательства, вот это вот все
        url(r'^collection/(?P<pk>[0-9]+)/$', views.coll_detail, name='coll_detail'),
        url(r'^publisher/(?P<pk>[0-9]+)/$', views.pub_detail, name='pub_detail'),
        url(r'^authors/(?P<pk>[0-9]+)/$', views.author_detail, name='author_detail'),
        url(r'^authors/$', views.authors_list, name='authors_list'),
        url(r'^authors/new$', views.author_new, name='author_new'),
        url(r'^collections/$', views.collections_list, name='collections_list'),
        url(r'^publishers/$', views.publishers_list, name='publishers_list'),
        url(r'^collection/new/$', views.collection_new, name='collection_new'),
        url(r'^publisher/new/$', views.pub_new, name='pub_new'),


        url(r'^my/$', views.my_works, name='my_lit_works'),

        url(r'^tags/new/(?P<id>[0-9]+)/(?P<type>sentence|word|paragraph|text)/$', views.add_tag, name='add_tag'),

        url(r'^add_mark/(?P<pk>[0-9]+)/(?P<type>work|word)/$', views.add_mark, name='add_mark'),
        url(r'^view_mark/(?P<pk>[0-9]+)/$',views.view_mark, name='view_mark')

    ]

diploma_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('cabinet.urls')),
]

cabinet/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import re
import pymysql
import math
import pymorphy2
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.apps import apps
db= pymysql.connect(host='localhost', user='val', passwd='111111111', db='diploma_project' , charset='utf8')
import codecs
from pynlpl.formats import folia, fql, cql
# from pytz import timezone
# Create your models here.
#     let's use existing django-model now
# class User(models.Model) :

# модель правок
class Marks(models.Model):
    verbose_name=u'Правки'
    object=models.IntegerField(verbose_name = _(u'Объект'))
    object_type = models.CharField(verbose_name=_(u'Тип объекта'), max_length=100)
    none = 'N'
    fields=((none,''),)
    field = models.CharField(verbose_name=_(u'Поле'), max_length=100, choices=fields)
    value = models.CharField(verbose_name=_(u'Значение'), max_length=100)
    author = models.ForeignKey('auth.User',verbose_name=_(u'Автор'))

 # модель абзаца
class Paragraph(models.Model):
    verbose_name = u'Абзацы'
    value = models.CharField(verbose_name = _(u'Абзац'), max_length=3000, null=True)
    lit_work = models.ForeignKey('LitWork', verbose_name=_(u'Литературное произведение'))

    # разбиение на предложения
    def parse_sentences(self, morph):
        cur = db.cursor()
        cur.execute("SET NAMES utf8mb4;")  # or utf8 or any other charset you want to handle
        cur.execute("SET CHARACTER SET utf8mb4;")  # same as above
        cur.execute("SET character_set_connection=utf8mb4;")  # same as above
        # разбиение по знакам препинания, на которые предложение оканчивается
        sentences = re.split('\n|\.\.\. |\! |\? |\. ', self.value)
        for s in sentences:
            with db:
                cur.execute('INSERT INTO cabinet_sentence (value, paragraph_id) values( "' +s+'", '+str(self.id)+ ')')
                # new_s = Paragraph.objects.create(value=s,paragraph_id=self.id)
                # и сразу каждый абзац на предложения
            Sentence.objects.latest('id').parse_words(morph)
        return self

 # модель предложения
class Sentence(models.Model):
    verbose_name = u'Предложения'
    value = models.CharField(verbose_name=_(u'Предложение'), max_length=500, null=True)
    paragraph = models.ForeignKey(Paragraph, verbose_name=_(u'Абзац'))

    # разбиение предложений на слова
    def parse_words(self, morph):
        cur = db.cursor()
        cur.execute("SET NAMES utf8mb4;")  # or utf8 or any other charset you want to handle
        cur.execute("SET CHARACTER SET utf8mb4;")  # same as above
        cur.execute("SET character_set_connection=utf8mb4;")  # same as above

        # разбиение предложения по любым знакам препинания и пробелам
        words = re.findall(r"[\w']+", str.lower(self.value))
        POSes = {'NOUN', 'VERB', 'ADJF', 'PRTF', 'GRND', 'NPRO', 'COMP', 'PRTS', 'INTJ', 'PRCL', 'ADJS', 'NUMR',
                 'ADVB'}
        # take infinitives
        normal_words = []
        for nw in words[:-1]:
            # pymorphy разбирает слова по морфологии
            parsed = morph.parse(nw)

            for p in parsed:
                normal_words.append(parsed[0].normal_form)
                # в базу будут сохраняться переведенные на киррилицу морфологические свойства. Юзеру так будет приятнее.
                MarkUp.objects.create(word=nw,
                                      grammem=morph.lat2cyr(str(p.tag.POS)),
                                      animacy=morph.lat2cyr(str(p.tag.animacy)),
                                      aspect=morph.lat2cyr(str(p.tag.aspect)),
                                      case=morph.lat2cyr(str(p.tag.case)),
                                      involvement=morph.lat2cyr(str(p.tag.involvement)),
                                      mood=morph.lat2cyr(str(p.tag.mood)),
                                      number=morph.lat2cyr(str(p.tag.number)),
                                      person=morph.lat2cyr(str(p.tag.person)),
                                      tense=morph.lat2cyr(str(p.tag.tense)),
                                      transitivity=morph.lat2cyr(str(p.tag.transitivity)),
                                      voice=morph.lat2cyr(str(p.tag.voice)),
                                      count=0,
                                      sentence_id=self.id)
            Word.objects.create(value = nw,
                                Sentence_id = self.id,
                                mark_up_id = MarkUp.objects.filter(word=nw).first().id)
        # create the dictionary
        normals = set(normal_words)
        dictionary = {w: 0 for w in normals}
        # подсчет слов с одинаковыми разборами
        for w in dictionary:
            parsed = morph.parse(w)
            if parsed[0].normal_form in normal_words:
                dictionary[parsed[0].normal_form] += 1
        for w in words:
            for key in dictionary:
                if morph.parse(w)[0].normal_form == key:
                    with db:
                        # изменение количества раз, сколько встретилось слово
                        cur.execute('UPDATE cabinet_markup SET count = ' + str(
                            dictionary[key]) + ' WHERE word = "' + w + '" and sentence_id = ' + str(self.id))
        frequent = {w: dictionary[w] for w in dictionary.keys() if dictionary[w] > 1}
        return self

 # модель пользовательских тегов
class Tags(models.Model):
    user = 'ur'
    system = 'ss'
    lingua = 'LG'
    library = 'LB'
    prosody = 'PS'
    narratology = 'NL'
    custom = 'CS'
    authority = ((user,'Пользовательский'),(system,'Системный'))
    version_types = ((custom, 'Пользовательский'),(lingua, 'Лингвистический'), (library, 'Словарный'), (prosody, 'Стиховедческий'), (narratology, 'Нарратологический'))
    category = models.CharField(null=False, blank=False,
                                choices=version_types, default=lingua, max_length=50, verbose_name=_(u'Категория'))
    content = models.CharField(blank=False, null=False, max_length=50, verbose_name=_(u'Описание'))
    author_type = models.CharField(blank=False, null=False, max_length=50, verbose_name=_(u'Авторство'),choices=authority, default=system)
    el_type = models.CharField(blank=False, null=False, max_length=50, verbose_name=_(u'Тип объекта'))
    el_id = models.IntegerField(blank=False, null=False, verbose_name=_(u'Объект'))
    owner = models.ForeignKey('auth.User', verbose_name=_(u'Владелец'))
    created_date = models.DateTimeField(default=timezone.now, verbose_name=_(u'Дата создания'))
    updated_date = models.DateTimeField(blank=True, null=True, verbose_name=_(u'Дата изменения'))

 # модель автора произведения
class Author(models.Model):
    verbose_name = u'Авторы'
    last_name = models.CharField(max_length=50, verbose_name = _(u'Фамилия'))
    first_name = models.CharField(max_length=50, verbose_name = _(u'Имя'))
    second_name = models.CharField(max_length=50, verbose_name = _(u'Отчество'))
    birth_date = models.DateTimeField(blank = True, null = True, verbose_name = _(u'Дата рождения'))
    death_date = models.DateTimeField(blank=True, null=True, verbose_name = _(u'Дата смерти'))
    country = models.CharField(max_length=80, verbose_name = _(u'Страна'))
    owner = models.ForeignKey('auth.User', verbose_name=_(u'Владелец'))
    created_date = models.DateTimeField(default=timezone.now, verbose_name=_(u'Дата создания'))
    updated_date = models.DateTimeField(blank=True, null=True, verbose_name=_(u'Дата изменения'))

    def __str__(self):
        return self.last_name+' '+self.first_name

 # модель издательства
class PublishingHouse(models.Model):
    verbose_name = u'Издательства'
    title = models.CharField(max_length=80, verbose_name = _(u'Издательство'))
    country = models.CharField(max_length=80, verbose_name = _(u'Страна'))
    owner = models.ForeignKey('auth.User', verbose_name=_(u'Владелец'))
    created_date = models.DateTimeField(default=timezone.now, verbose_name=_(u'Дата создания'))
    updated_date = models.DateTimeField(blank=True, null=True, verbose_name=_(u'Дата изменения'))
    def __str__(self):
        return self.title


 # модель коллекции
class Collection(models.Model):
    verbose_name = u'Коллекции'
    title = models.CharField(max_length=200, verbose_name = _(u'Коллекция'))
    owner = models.ForeignKey('auth.User', verbose_name = _(u'Владелец'))
    created_date = models.DateTimeField(
        default=timezone.now, verbose_name = _(u'Дата создания'))
    updated_date = models.DateTimeField(
        blank = True, null=True, verbose_name = _(u'Дата последнего обновления'))
    is_open = models.BooleanField(default = False, verbose_name = _(u'Доступность'))
    def __str__(self):
        return self.title

 # модель разметки
class MarkUp(models.Model):
    word = models.CharField( blank=False, max_length=100, verbose_name = _(u'Слово'))
    grammem = models.CharField( blank=False, max_length=100, verbose_name = _(u'Часть речи'))
    animacy = models.CharField(blank=False, max_length=100, verbose_name = _(u'Одушевленность'))# одушевленность
    aspect = models.CharField( blank=False, max_length=100, verbose_name = _(u'Вид'))# вид: совершенный или несовершенный
    case = models.CharField( blank=False, max_length=100, verbose_name = _(u'Падеж'))# падеж
    gender = models.CharField( blank=False, max_length=100, verbose_name = _(u'Род'))# род (мужской, женский, средний)
    involvement = models.CharField( blank=False, max_length=100, verbose_name = _(u'Говорящий')) # включенность говорящего в действие
    mood = models.CharField( blank=False, max_length=100, verbose_name = _(u'Наклонение')) # наклонение (повелительное, изъявительное)
    number = models.CharField( blank=False, max_length=100, verbose_name = _(u'Число')) # число (единственное, множественное)

cabinet/templates/cabinet/add_authors.html
{# шаблон добавления соавторов #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
{% block content %}
    <h1>Добавить соавтора</h1>
    <div>
        <form enctype="multipart/form-data" method="POST" class="post-form">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
    <script>
        $(document).ready(function () {
            path = document.location.pathname.split('/');
            $('#id_work').val(path[2]);
            $('#id_work').attr('disabled','disabled');
        });
    </script>
{% endblock %}

cabinet/templates/cabinet/add_tag.html
{# шаблон добавления пользовательского тега  #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
{% block content %}
    <h1>Добавление тега</h1>
    <div>
        <form enctype="multipart/form-data" method="POST" class="post-form">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
    <script>
        $(document).ready(function () {
            {# учитываем, к чему этот тег добавляется #}
            path = document.location.pathname.split('/');
            type = $('#id_el_type');
            $(type).val(path[4]);
            $(type).attr('disabled','disabled');
            $('#id_el_id').val(path[3]);
            $('#id_el_id').attr('disabled','disabled');
        });
    </script>
{% endblock %}

cabinet/templates/cabinet/author_detail.html
{# шаблом формы просмотра инфо о соавторе #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
{% block content %}
    <div class="article">
        <h1>Просмотр сведений об авторе</h1>
        <table>
            <tr>
                <th>Фамилия: </th><td>{{ a.last_name|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Имя: </th><td>{{ a.first_name|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Отчество: </th><td>{{ a.second_name|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Дата рождения: </th><td>{{ a.birth_date|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Дата смерти: </th><td>{{ a.death_date|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Страна: </th><td>{{ a.country|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Добавлено: </th><td>{{ a.created_date|linebreaksbr }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

cabinet/templates/cabinet/authors_list.html
{# шаблон списка авторов #}
 {% extends 'cabinet/lit_work_show.html' %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block content %}
        {% if user.is_authenticated %}
            {% for au in authors %}
                <div class="article">
                  <h2> <a style="color: white" href="#">{{ au.last_name }} {{ au.first_name }}</a></h2>
                  <div class="clr"></div>
                  <p class="infopost">Опубликовано <span class="date">{{ au.created_date }}</span> <a href="#">{{ au.owner }}</a> &nbsp;|&nbsp; </p>
                  <p class="spec"><a href="{% url 'author_detail' pk=au.pk %}" class="rm">Узнать больше &raquo;</a></p>
                </div>
            {% endfor %}
        {% else %}
            <div class="article">
                <h2> <a href=" {% url 'auth_login' %}" >Авторизуйтесь</a> , чтобы просматривать список авторов. </h2>
            </div>
        {% endif %}
    {% endblock content %}

cabinet/templates/cabinet/collection_new.html
{# шаблон добавления новой коллекции #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block content %}
        <h1>Коллекция</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
            <input type="submit" value="Сохранить"/>
        </form>
    {% endblock %}

cabinet/templates/cabinet/collections_list.html
{# шаблон списка коллекций #}
 {% extends 'cabinet/lit_work_show.html' %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block content %}
        <h2>Коллекции</h2>
        {% if user.is_authenticated %}
            {% for au in collections %}
                <div class="article">
                  <h3> <a href="#">{{ au.title }}</a></h3>
                  <div class="clr"></div>
                  <p class="infopost">Добавлена <a href="#">{{ au.owner }}</a> <span class="date">{{ au.created_date }}</span>  &nbsp;|&nbsp; </p>
                    <p class="content">{{ au.sub_title|linebreaksbr }}</p>
                    <p class="content">{{ au.collection|linebreaksbr }}</p>
                  <p class="spec"><a href="#" class="rm">Узнать больше &raquo;</a></p>
                </div>
            {% endfor %}
        {% else %}
            <div class="article">
                <h2> <a href=" {% url 'auth_login' %}" >Авторизуйтесь</a> , чтобы просматривать список авторов. </h2>
            </div>
        {% endif %}
    {% endblock content %}

cabinet/templates/cabinet/lit_work_list.html
{# шаблон списка текстов #}
 {% extends 'cabinet/lit_work_show.html' %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block content %}
        {% if user.is_authenticated %}
            {% for work in works %}
                {% if work.is_editable == True %}
                    <div class="article">
                      <h2> <a style="text-transform: uppercase; color: white;" href="{% url 'work_detail' pk=work.pk %}">{{ work.title }}</a></h2>
                      <div class="clr"></div>
                        <p class="infopost">Опубликовано <span class="date">{{ work.created_date }}</span> пользователем <span style="text-transform: uppercase">{{ work.owner }}</span> &nbsp;|&nbsp; </p>
                        <p class="content">{{ work.sub_title|linebreaksbr }}</p>
                        <p class="content">{{ work.collection|linebreaksbr }}</p>
                      <p class="spec"><a href="{% url 'work_detail' pk=work.pk %}" class="rm">Узнать больше &raquo;</a></p>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div class="article">
                <h2> <a href=" {% url 'auth_login' %}" >Авторизуйтесь</a> , чтобы просматривать существующие тексты. </h2>
            </div>
        {% endif %}
    {% endblock content %}

cabinet/templates/cabinet/lit_work_show.html
{# шаблон layout  #}
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.0.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="//cdn.rawgit.com/rainabba/jquery-table2excel/1.1.0/dist/jquery.table2excel.min.js"></script>
    <title>Лингвистическая платформа</title>
</head>
<body class=" dashboard">
<div id="container">
    <div style="min-height: 100%">
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'lit_work_list' %}">Сервис лингвистической разметки</a></h1>
            </div>
            <div id="user-tools">
                <a href="{% url 'work_filters' %}"> Перейти к разметке</a><span> / </span>
                <a href="https://github.com/valkharb/lingua_crowdsource"> Связаться с автором </a><span> / </span>
                {% if user.is_authentificated == True or user.is_anonymous != True%}
                    <a href="{% url 'account' pk=user.pk %}">Личный кабинет</a>
                {% else %}
                    <a href="{% url 'auth_login' %}">Войти в систему</a>
                {% endif %}
            </div>
        </div>
        <div id="content" class="colMS">
            <div id="content-main">
                <div class="app-cabinet module">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div id="content-related">
                <div class="module" id="recent-actions-module">
                    <ul class="actionlist">
                        <li class="addlink"><a href="{% url 'lit_work_list' %}">Доступные тексты</a></li>
                        <li class="addlink"><a href="{% url 'my_lit_works' %}">Мои тексты</a></li>
                        <li class="addlink"><a href="{% url 'authors_list' %}">Авторы</a></li>
                        <li class="addlink"><a href="{% url 'collections_list' %}">Коллекции</a></li>
                        <li class="addlink"><a href="{% url 'publishers_list' %}">Издательства</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="footer_resize">
            <p class="lf">Copyright &copy; <a href="#">Higher School of Economics</a>. All Rights Reserved</p>
            <p class="rf">Get More info about <a target="_blank" href="http://www.hse.ru/"> NRU HSE </a></p>
            <div class="clr"></div>
        </div>
    </div>
</div>
</body>
</html>

cabinet/templates/cabinet/my.html
{# шаблон произведений пользователя #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
{% block content %}
    {% if user.is_authenticated %}
        {% for work in works %}
            <div class="article">
                <h2> <a style="text-transform: uppercase; color: white;" href="{% url 'work_detail' pk=work.pk %}">{{ work.title }}</a></h2>
                <div class="clr"></div>
                <p class="infopost">Опубликовано <span class="date">{{ work.created_date }}</span> <a href="#">{{ work.owner }}</a> &nbsp;|&nbsp; </p>
                <p class="content">{{ work.sub_title|linebreaksbr }}</p>
                {% if work.collection %}
                    <p class="content">{{ work.collection|linebreaksbr }}</p>
                {% endif %}
                <p class="spec"><a href="{% url 'work_detail' pk=work.pk %}" class="rm">Узнать больше &raquo;</a></p>
            </div>
        {% endfor %}
    {% else %}
        <div class="article">
            <h2> <a href=" {% url 'auth_login' %}" >Авторизуйтесь</a> , чтобы просматривать существующие тексты. </h2>
        </div>
    {% endif %}
{% endblock content %}

cabinet/templates/cabinet/pub_detail.html
{# шаблон  инфо об издательстве #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
{% block content %}
    <div class="article">
        <h1>Просмотр сведений об издательстве</h1>
        <table>
            <tr>
                <th>Страна: </th><td>{{ pub.country|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Наименование: </th><td>{{ pub.title|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Дата создания: </th><td>{{ pub.created_date|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Добавлено: </th><td>{{ pub.owner|linebreaksbr }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

cabinet/templates/cabinet/pub_new.html
{# шаблон нового издательства #}
{% extends 'cabinet/lit_work_show.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block content %}
        <h1>Издательство</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
            <input type="submit" value="Сохранить"/>
        </form>
    {% endblock %}

cabinet/templates/cabinet/show_filters.html
{# шаблон фильтров #}
 {% extends 'cabinet/lit_work_show.html' %}
    {% load staticfiles %}

    {% block content %}
        <table>
            <form method="POST" class="post-form">{% csrf_token %}
               {{ form.as_table }}
            </form>
        </table>
    {% endblock content %}

<script>

    </script>